backend/src/Domain/Todos/Task/Entity/File.php
<?php

declare(strict_types=1);

namespace App\Domain\Todos\Task\Entity;

use App\Domain\Todos\Task\Entity\Task\Task;
use Ramsey\Uuid\Uuid;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Serializer\Annotation\Groups;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Image
 * @ORM\Entity()
 * @ORM\Table(
 *     name="task_file",
 *     uniqueConstraints={@ORM\UniqueConstraint(columns={"filename"})}
 * )
 */
class File
{
    /**
     * @var string
     * @ORM\Column(type="guid")
     * @ORM\Id()
     * @Groups({"show_files"})
     */
    private string $id;
    /**
     * @var Task
     * @ORM\ManyToOne(targetEntity="App\Domain\Todos\Task\Entity\Task\Task", inversedBy="files")
     * @ORM\JoinColumn(name="task_id", referencedColumnName="id", nullable=false, onDelete="CASCADE")
     */
    private Task $task;
    /**
     * @var string
     * @ORM\Column(type="string", length=150, nullable=false)
     * @Groups({"show_files"})
     */
    private string $filename;
    /**
     * @var string
     * @ORM\Column(type="string", length=150, nullable=false)
     * @Groups({"show_files"})
     */
    private string $originalFilename;
    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private string $filepath;
    /**
     * @var boolean
     * @ORM\Column(type="boolean")
     * @Groups({"show_files"})
     */
    private bool $isActive;
    /**
     * @var string
     * @ORM\Column(type="string", length=150, nullable=true)
     * @Groups({"show_files"})
     */
    private string $mimeType;
    /**
     * @var \DateTimeImmutable
     * @ORM\Column(type="datetime_immutable", length=150, nullable=false)
     * @Groups({"show_files"})
     */
    private \DateTimeImmutable $createdAt;

    public function __construct(string $filename, UploadedFile $uploadedFile, Task $task)
    {
        $this->id = Uuid::uuid4()->toString();
        $this->filename = $filename;
        $this->task = $task;
        $this->originalFilename = $uploadedFile->getClientOriginalName();
        $this->mimeType = $uploadedFile->getMimeType();
        $this->createdAt = new \DateTimeImmutable();
        $this->filepath = $this->getFileDirectory();
        $this->setActive();
    }

    /**
     * @return string
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * @return Task
     */
    public function getUser(): Task
    {
        return $this->task;
    }

    /**
     * @param Task $task
     */
    public function setUser(Task $task): void
    {
        $this->task = $task;
    }

    /**
     * @return string
     */
    public function getFilename(): string
    {
        return $this->filename;
    }

    /**
     * @param string $filename
     */
    public function setFilename(string $filename): void
    {
        $this->filename = $filename;
    }

    /**
     * @return string
     */
    public function getOriginalFilename(): string
    {
        return $this->originalFilename;
    }

    /**
     * @param string $originalFilename
     */
    public function setOriginalFilename(string $originalFilename): void
    {
        $this->originalFilename = $originalFilename;
    }

    /**
     * @return string
     */
    public function getMimeType(): string
    {
        return $this->mimeType;
    }

    /**
     * @param string $mimeType
     */
    public function setMimeType(string $mimeType): void
    {
        $this->mimeType = $mimeType;
    }

    /**
     * @return \DateTimeImmutable
     */
    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTimeImmutable $createdAt
     */
    public function setCreatedAt(\DateTimeImmutable $createdAt): void
    {
        $this->createdAt = $createdAt;
    }
    /**
     * @param string $filename
     * @return bool
     */
    public function isFileAttached(string $filename): bool
    {
        return $this->filename === $filename;
    }

    /**
     * @return string
     */
    public function getFileDirectory(): string
    {
        if (isset($this->filepath)) {
            return $this->filepath;
        }

        if ($this->task) {
            return (new \ReflectionClass($this->task))->getShortName() . DIRECTORY_SEPARATOR . $this->task->getId()->getValue();
        }

        return '';
    }

    /**
     * @return string
     */
    public function getFilePath(): string
    {
        if ($fileDirectory = $this->getFileDirectory()) {
            return $fileDirectory . DIRECTORY_SEPARATOR . $this->filename;
        }

        return '';
    }

    /**
     * @param string $filepath
     */
    public function setFilepath(string $filepath): void
    {
        $this->filepath = $filepath;
    }

    /**
     * @return bool
     */
    public function isActive(): bool
    {
        return $this->isActive;
    }


    public function setActive(): void
    {
        $this->isActive = true;
    }

    public function setInactive(): void
    {
        $this->isActive = false;
    }
}

backend/src/Http/Controller/User/Profile/EmailController.php
<?php

declare(strict_types=1);

namespace App\Http\Controller\User\Profile;

use App\Domain\Auth\User\UseCase;
use App\Domain\Auth\User\Entity\User\Id;
use App\Domain\Auth\User\Repository\UserRepository;
use App\Domain\Auth\User\Service\NewEmailConfirmTokenizer;
use Psr\Log\LoggerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

/**
 * @Route("/profile/email")
 * Class EmailController
 * @package App\Controller\Profile
 */
class EmailController extends AbstractController
{
    private LoggerInterface $logger;
    private UserRepository $userRepository;

    /**
     * EmailController constructor.
     * @param LoggerInterface $logger
     * @param UserRepository $userRepository
     */
    public function __construct(
        LoggerInterface $logger,
        UserRepository $userRepository
    )
    {
        $this->logger = $logger;
        $this->userRepository = $userRepository;
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("", name="profile.email")
     * @param Request $request
     * @param UseCase\Email\ChangeRequest\Handler $handler
     * @param NewEmailConfirmTokenizer $tokenizer
     * @return Response
     */
    public function request(
        Request $request,
        UseCase\Email\ChangeRequest\Handler $handler,
        NewEmailConfirmTokenizer $tokenizer
    ): Response
    {
        $token = $tokenizer->generate();
        $confirmUrl = $this->generateUrl(
            'profile.email_confirm',
            ['token' => $token],
            UrlGeneratorInterface::ABSOLUTE_URL
        );

        $command = (new UseCase\Email\ChangeRequest\Command())
            ->setId($this->getUser()->getId())
            ->setToken($token)
            ->setConfirmUrl($confirmUrl);

        $form = $this->createForm(UseCase\Email\ChangeRequest\Form::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $handler->handle($command);
                $this->addFlash('success', 'Check your email.');
                return $this->redirectToRoute('profile');
            } catch (\DomainException $e) {
                $this->logger->error($e->getMessage(), ['exception' => $e]);
                $this->addFlash('error', $e->getMessage());
            }
        }

        return $this->render('app/profile/email.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/confirm/{token}", name="profile.email_confirm")
     * @param $token
     * @param UseCase\Email\Confirm\Handler $handler
     * @return Response
     */
    public function confirm($token, UseCase\Email\Confirm\Handler $handler): Response
    {
        $command = new UseCase\Email\Confirm\Command($this->getUser()->getId(), $token);

        try {
            $handler->handle($command);
            $this->addFlash('success', 'Email is successfully changed.');
            return $this->redirectToRoute('profile');
        } catch (\Exception $e) {
            $this->logger->error($e->getMessage(), ['exception', $e]);
            $this->addFlash('error', $e->getMessage());
            return $this->redirectToRoute('profile');
        }
    }

    /**
     * @Route("/confirm-page/{token}", name="profile.email_confirm_page")
     * @param $token
     * @param UseCase\Email\Confirm\Handler $handler
     * @param Request $request
     * @return Response
     */
    public function confirmWithRedirectToPage($token, UseCase\Email\Confirm\Handler $handler, Request $request): Response
    {
        try {
            $user = $this->userRepository->getById(
                new Id($request->query->get('user_id'))
            );
        } catch (\Exception $e) {
            throw new NotFoundHttpException('User not found.');
        }

        $command = new UseCase\Email\Confirm\Command($user->getId()->getValue(), $token);
        $pathToUi = $this->getParameter('ui_host');

        try {
            $handler->handle($command);
            $this->addFlash('success', 'Email is successfully changed.');
        } catch (\Exception $e) {
            $this->addFlash('error', $e->getMessage());
        }

        return $this->render('app/profile/confirm-email.html.twig', compact('pathToUi'));
    }
}

backend/src/Http/Controller/User/Profile/NameController.php
<?php

declare(strict_types=1);

namespace App\Http\Controller\User\Profile;

use App\Domain\Auth\User\UseCase;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @IsGranted("ROLE_USER")
 * @Route("/profile/name")
 * Class NameController
 * @package App\Controller\Profile
 */
class NameController extends AbstractController
{
    private LoggerInterface $logger;
    private TranslatorInterface $translator;

    /**
     * NameController constructor.
     * @param TranslatorInterface $translator
     * @param LoggerInterface $logger
     */
    public function __construct(
        TranslatorInterface $translator,
        LoggerInterface $logger
    )
    {
        $this->logger = $logger;
        $this->translator = $translator;
    }

    /**
     * @Route("/{id}", name="profile.change_name")
     * @param string $id
     * @param Request $request
     * @param UseCase\Name\Handler $handler
     * @return Response
     */
    public function changeUserName(string $id, Request $request, UseCase\Name\Handler $handler): Response
    {
        $command = new UseCase\Name\Command($id);

        $form = $this->createForm(UseCase\Name\Form::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $handler->handle($command);
                $this->addFlash('success', $this->translator->trans("User's first and last name updated.", [], 'profile'));
                return $this->redirectToRoute('profile');
            } catch (\DomainException $e) {
                $this->logger->error($e->getMessage(), ['exception' => $e]);
                $this->addFlash('error', $e->getMessage());
            }
        }

        return $this->render('app/profile/name.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

backend/src/Http/Controller/User/Profile/ProfileController.php
<?php

declare(strict_types=1);

namespace App\Http\Controller\User\Profile;

use App\Domain\Auth\User\UseCase;
use App\Domain\Auth\User\Entity\User\Id;
use App\Domain\Auth\User\Repository\ImageRepository;
use App\Domain\Auth\User\Repository\UserRepository;
use App\Infrastructure\Upload\UploadHelper;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mime\MimeTypesInterface;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\ConstraintViolation;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @IsGranted("ROLE_USER")
 * Class ProfileController
 * @package App\Controller\Profile
 */
class ProfileController extends AbstractController
{
    private UserRepository $users;
    private ValidatorInterface $validator;
    private MimeTypesInterface $mimeTypes;
    private UploadHelper $uploadHelper;
    private LoggerInterface $logger;
    private ImageRepository $images;

    /**
     * ProfileController constructor.
     * @param UserRepository $users
     * @param ImageRepository $images
     * @param ValidatorInterface $validator
     * @param MimeTypesInterface $mimeTypes
     * @param LoggerInterface $logger
     */
    public function __construct(
        UserRepository $users,
        ImageRepository $images,
        ValidatorInterface $validator,
        MimeTypesInterface $mimeTypes,
        LoggerInterface $logger
    )
    {
        $this->users = $users;
        $this->validator = $validator;
        $this->mimeTypes = $mimeTypes;
        $this->logger = $logger;
        $this->images = $images;
    }

    /**
     * @Route("/profile", name="profile")
     * @return Response
     */
    public function index(): Response
    {
        $user = $this->users->getById(new Id($this->getUser()->getId()));
        $activeImage = $this->images->findActiveImageByUserId($user->getId());
        return $this->render('app/profile/show.html.twig', compact('user', 'activeImage'));
    }

    /**
     * @Route("/profile/image-upload", name="profile.image_upload")
     * @param Request $request
     * @param UseCase\Image\Attach\Handler $handler
     * @return Response
     */
    public function uploadProfileImage(Request $request, UseCase\Image\Attach\Handler $handler): Response
    {
        /** @var UploadedFile $uploadedFile */
        $uploadedFile = $request->files->get('cropped-image');

        $violations = $this->validator->validate($uploadedFile, [
           new NotBlank(),
           new File([
               'maxSize' => '5M',
               'mimeTypes' => \array_merge($this->mimeTypes->getMimeTypes('jpeg'), $this->mimeTypes->getMimeTypes('png'))
           ])
        ]);

        $responseData['error'] = false;

        if ($violations->count() > 0) {
            /** @var ConstraintViolation $violation */
            $violation = $violations[0];
            $responseData['error'] = true;
            $responseData['message'] = $violation->getMessage();

            return $this->json($responseData, 422);
        }

        $command = new UseCase\Image\Attach\Command($uploadedFile, $request->get('user-id'));

        try {
            $handler->handle($command);
        } catch (\Exception $e) {
            $responseData['error'] = true;
            $responseData['message'] = $e->getMessage();

            return $this->json($responseData, 422);
        }

        return $this->json($responseData);
    }
}

backend/templates/app/profile/confirm-email.html.twig
{% extends 'info.html.twig' %}

{% block title %}Confirm email{% endblock %}

{% block body %}
    <div class="row">
        <div class="col text-center">
            <a href="{{ pathToUi }}" class="btn btn-lg btn-outline-success">Back to UI</a>
        </div>
    </div>
{% endblock %}

backend/templates/app/profile/email.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Profile{% endtrans %}{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item">{% trans from 'profile'%}User profile{% endtrans %}</li>
    <li class="breadcrumb-item active">{% trans %}Email{% endtrans %}</li>
{% endblock %}

{% block body %}

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    {{ form_start(form) }}
                    {{ form_widget(form) }}
                    <button type="submit" class="btn btn-success">{% trans %}Save{% endtrans %}</button>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

backend/templates/app/profile/name.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Changing user name{% endtrans %}{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item">{% trans from 'profile'%}User profile{% endtrans %}</li>
    <li class="breadcrumb-item active">{% trans %}Changing user name{% endtrans %}</li>
{% endblock %}

{% block body %}

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    {{ form_start(form) }}
                    <div class="form-group">
                        {{ form_label(form.first, 'First name'|trans({}, 'app')) }}
                        {{ form_widget(form.first) }}
                    </div>
                    <div class="form-group">
                        {{ form_label(form.last, 'Last name'|trans({}, 'app')) }}
                        {{ form_widget(form.last) }}
                    </div>
                    <button type="submit" class="btn btn-success">{% trans %}Save{% endtrans %}</button>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

backend/templates/app/profile/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active">{% trans from 'profile' %}User profile{% endtrans %}</li>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('profile-page') }}
{% endblock %}

{% block body %}

    <div class="row mb-2">
        <div class="col">

            <div style="max-width: 600px; ">
                <img id="profile-image" src="{{
                activeImage
                    ? uploaded_asset(activeImage.getFilepath)
                    : asset('img/user_default_img.png')
                }}" data-user-id="{{ user.id }}" data-image-name="Работа.jpg" alt="">
            </div>

        </div>
    </div>
    
    <div class="row mb-4">
        <div class="col">

            <div class="d-flex">
                <div class="mr-1">
                    <label class="btn btn-outline-dark" for="cropper-input">
                        <input type="file" id="cropper-input" class="sr-only" accept="image/*">
                        <span class="mr-1">{% trans from 'profile' %}Load photo{% endtrans %}</span>
                        <i class="fas fa-download"></i>
                    </label>
                </div>
                <div>
                    <button id="js-upload-cropper-image" type="button" class="btn btn-outline-success">
                        <span class="mr-1">{% trans %}Save{% endtrans %}</span><i class="fas fa-cloud-upload-alt"></i>
                    </button>
                </div>
            </div>
        </div>

    </div>

    <div class="row mb-4">
        <div class="col">
            <div class="d-flex">

                {% for image in user.images %}
                    <img class="mr-1" src="{{ image.filePath|imagine_filter('squared_thumbnail_xs') }}" alt="" height="100">
                {% endfor %}

            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header"><h5>{% trans from 'profile' %}Profile{% endtrans %}</h5></div>
                <div class="card-body">
                    <table class="table table-bordered table-hover">
                        <tbody>
                            <tr>
                                <td>{% trans %}Name{% endtrans %}</td>
                                <td>
                                    {{ user.name.full }}
                                    <a href="{{ path('profile.change_name', {id: user.id}) }}" class="btn btn-sm btn-outline-primary">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>
                                </td>
                            </tr>
                            {% if user.email %}
                                <tr>
                                    <td>Email</td>
                                    <td>
                                        {{ user.email }}
                                        <a href="{{ path('profile.email') }}" class="btn btn-sm btn-outline-primary">
                                            <i class="fas fa-pencil-alt"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endif %}
                            <tr>
                                <td>{% trans %}Created{% endtrans %}</td>
                                <td>{{ user.date|date('d.m.Y H:i:s') }}</td>
                            </tr>
                            <tr>
                                <td>{% trans %}Role{% endtrans %}</td>
                                <td>{{ user_role(user.role.name) }}</td>
                            </tr>
                            <tr>
                                <td>{% trans %}Status{% endtrans %}</td>
                                <td>{{ user_status(user.status) }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header"><h5>{% trans %}Networks{% endtrans %}</h5></div>
                    <div class="card-body">
                        {% if user.networks %}
                            <table class="table table-bordered table-hover">
                                <tbody>
                                    {% for network in user.networks %}
                                        <tr>
                                            <td>{{ network.network }}</td>
                                            <td>{{ network.identity }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        {% endif %}
                        <a class="btn btn-info" href="{{ path('oauth.attach.vkontakte') }}">{% trans %}Attach VK{% endtrans %}</a>
                    </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('profile-page') }}
{% endblock %}